on:
  push:
    branches:
      - main
    paths:
      - 'bot/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build and push image
        run: |
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD=${{ secrets.DOCKERHUB_PASSWORD }}


          if [[ -z $DOCKERHUB_USERNAME ]] || [[ -z $DOCKERHUB_PASSWORD ]]; then
            echo DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD secrets should be configured
            exit 1
          fi

          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
          echo "login success"

          IMAGE_NAME=$DOCKERHUB_USERNAME/saferoombot:${{ github.run_number }}
          latest=$DOCKERHUB_USERNAME/saferoombot:latest
          cd bot
          echo $(ls)
          docker build -t $IMAGE_NAME .
          echo "New Docker build"
          docker push $IMAGE_NAME
          docker build -t $latest --push .

  